name: Tests

# on:
#   push:
#     branches:
#       - main
#       - 'release-*'
#   pull_request:
#     branches:
#       - main
#       - 'release-*'

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 1

      - name: Run e2e tests
        uses: ./.github/actions/e2e-tests

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 1

      - name: Run tests
        uses: ./.github/actions/unit-tests

  i18n:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 1

      - name: Run i18n lint
        uses: ./.github/actions/i18n-lint

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 1

      - name: Run tests
        uses: ./.github/actions/lint
